{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# -*- coding: utf-8 -*-\n",
    "\"\"\"\n",
    "#author: robert shava\n",
    "#project: SDG indicator 15.1.1: Forest area as a proportion of total land area\n",
    "\"\"\"\n",
    "#import libraries\n",
    "from pathlib import Path\n",
    "import geopandas as gpd\n",
    "import pandas as pd\n",
    "from pandas import DataFrame, merge\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import shapely\n",
    "import csv\n",
    "\n",
    "\"\"\"\n",
    "forests = [r'R:\\SDGs\\SDG_15_1_1\\data\\gb_nfi\\nfi_gb_2017.shp',r'R:\\SDGs\\SDG_15_1_1\\data\\gb_nfi\\nfi_gb_2018.shp',r'R:\\SDGs\\SDG_15_1_1\\data\\gb_nfi\\nfi_gb_2019.shp']\n",
    "lad19BFE = gpd.read_file(r'R:\\SDGs\\SDG_15_1_1\\data\\LAD\\Local_Authority_Districts__December_2019__Boundaries_UK_BFE.shp')\n",
    "display(lad19BFE.head())\n",
    "\n",
    "for forest in forests:\n",
    "    nfi = gpd.read_file(forest)\n",
    "    nfi.columns = nfi.columns.str.upper() # capitalise column names\n",
    "    filt_cat = (nfi['CATEGORY']=='Woodland') # filter olny Woodland from non-woodland\n",
    "    nfi_wood = nfi.loc[filt_cat]\n",
    "    nfi_wood_bng = nfi_wood.to_crs(27700) # convert crs to british national grid \n",
    "    display(nfi_wood_bng.head()) # check if code has run successfully\n",
    "\n",
    "\"\"\"\n",
    "# function to open geodataframe of shapefiles with specified parameters\n",
    "def open_geodataframe(shapefile_path: str, cols: list = None, index: str = None, epsg: int = 27700) -> gpd.GeoDataFrame : :\n",
    "    \n",
    "    \"\"\"\n",
    "    Returns gdf of shapefile. If cols is None, all cols will be returned, else only cols in a list. If index is None, no index will be set\n",
    "\n",
    "    Parameters:\n",
    "    -----------\n",
    "    shapefile_path (str):\n",
    "        Path to shapefile\n",
    "\n",
    "    cols (None/list):\n",
    "        Columns to select. If left as default (None), all columns will be selected (Default=None)\n",
    "\n",
    "    index (None/str):\n",
    "        Column to set as index. If left as default (None), no index will be set (Default=None)\n",
    "\n",
    "    epsg (int):\n",
    "        EPSG Code for gdf coordinate reference system\n",
    "\n",
    "    Returns:\n",
    "    --------\n",
    "    gdf (gpd.GeoDataFrame):\n",
    "        Geodataframe of shapefile opened with columns and index set as selected\n",
    "\n",
    "    \"\"\"\n",
    "    shp = Path(str(shapefile_path)).resolve()\n",
    "    gdf = gpd.read_file(shp)\n",
    "    if cols:\n",
    "        gdf = gdf[cols]\n",
    "    if index:\n",
    "        gdf = gdf.set_index(index)\n",
    "    if not gdf.crs.to_epsg() == epsg:  # Set the projection to that defined in epsg in the arguments\n",
    "        gdf = gdf.to_crs(epsg)\n",
    "    return gdf\n",
    "\n",
    "\n",
    "\n",
    "#function to open csv file as a pandas dataframe with specified parameters\n",
    "\n",
    "def open_dataframe_csv(csv_filepath: str, cols: list = None, index: str = None) -> pd.DataFrame :\n",
    "    \n",
    "    \"\"\"\n",
    "    Returns df of csv. If cols is None, all cols will be returned, else only cols in a list. If index is None, no index will be set\n",
    "\n",
    "    Parameters:\n",
    "    -----------\n",
    "    csv_path (str):\n",
    "        Path to csv\n",
    "\n",
    "    cols (None/list):\n",
    "        Columns to select. If left as default (None), all columns will be selected (Default=None)\n",
    "\n",
    "    index (None/str):\n",
    "        Column to set as index. If left as default (None), no index will be set (Default=None)\n",
    "\n",
    "    \n",
    "    Returns:\n",
    "    --------\n",
    "    df (pd.DataFrame):\n",
    "        pandas Dataframe of csv opened with columns and index set as selected\n",
    "        \n",
    "    \"\"\"\n",
    "    csv = Path(str(csv_filepath)).resolve()\n",
    "    df=pd.read_csv(csv)\n",
    "    if cols:\n",
    "        df = df[cols]\n",
    "    if index:\n",
    "        df = df.set_index(index)\n",
    "    return df\n",
    "\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    # import forest and lad boundaries as geodataframes and SAM as csv\n",
    "    nfi19ni = open_geodataframe(r'D:\\SDGs\\SDG_15_1_1\\data\\NIforest\\draftNIWoodlandBasemapAtApril2019.shp')\n",
    "    print(nfi19ni.head())\n",
    "    sam19lad = open_dataframe_csv(r'D:\\SDGs\\SDG_15_1_1\\data\\SAM_AdministrativeAreas_2019\\SAM_LAD_DEC_2019_UK.csv',cols=['LAD19CD','LAD19NM','AREALHECT'],index='LAD19CD')\n",
    "    print(sam19lad.head())\n",
    "    lad19bfe = open_geodataframe(r'D:\\SDGs\\SDG_15_1_1\\data\\LAD\\Local_Authority_Districts__December_2019__Boundaries_UK_BFE.shp')\n",
    "    print(lad19bfe.head())\n",
    "    # do spatial join between forest layer and lad boundaries layer\n",
    "    gdf_join_ni = gpd.sjoin(nfi19ni, lad19bfe, how='left')\n",
    "    print(gdf_join_ni.head())\n",
    "    # join gdf_join_ni and SAM csv to add lad area column to gdf_join_ni and calculate area\n",
    "    \n",
    "    \n",
    "\n",
    "\n",
    "    \n",
    "#intersect lad boundaries with forest layer to create a spatial join\n",
    "\n",
    "\n",
    "def do_spatial_join(gdf_LA: gpd.GeoDataFrame, gdf_forest: gpd.GeoDataFrame) -> gpd.GeoDataFrame :\n",
    "    \"\"\"\n",
    "    Returns spatial join of LAs with forests\n",
    "\n",
    "    Parameters:\n",
    "    -----------\n",
    "    gdf_LA (gpd.GeoDataFrame):\n",
    "        Geodataframe of Local Authorities\n",
    "\n",
    "    gdf_forest (gpd.GeoDataFrame):\n",
    "        Geodataframe of forests\n",
    "\n",
    "    Returns:\n",
    "    --------\n",
    "    gdf_join (gpd.GeoDataFrame):\n",
    "        GeodataFrame of forests joined to LAS\n",
    "-\n",
    "    \"\"\"\n",
    "    print(\"WRITE CODE TO DO JOIN AND RETURN JOINED GDF\")\n",
    "    gdf_join = gpd.sjoin(gdf_forest, gdf_LA, how='left')\n",
    "    return gdf_join\n",
    "\n",
    "do_spatial_join(nfi19ni, lad19bfe)\n",
    "\n",
    "gdf_join.head()\n",
    "    \n",
    "lad19bfe_sam = lad19bfe.merge(sam19lad, on='LAD19CD')    \n",
    "lad19bfe_sam.head()\n",
    "lad19bfe_sam.to_file(r'D:\\SDGs\\SDG_15_1_1\\intermediate\\lad19bfe_sam.shp')\n",
    "\n",
    "lad19bfe_samgpd = gpd.read_file(r'D:\\SDGs\\SDG_15_1_1\\intermediate\\lad19bfe_sam.shp')\n",
    "nfi19ni_lad19 = gpd.overlay(nfi19ni, lad19bfe_samgpd, how='intersection')\n",
    "nfi19ni_lad19.head()\n",
    "nfi19ni_lad19.to_file(r'D:\\SDGs\\SDG_15_1_1\\intermediate\\nfi19ni_lad19.shp')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "geo_env38",
   "language": "python",
   "name": "geo_env38"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
