name: CI

on:
  pull_request:
  push:
    branches:
      - "apprentice_rework*"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.8]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Update pip and install the package
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[test]"
      - name: Run tests
        run: |
          python -m unittest
      - name: Install and run linters
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == 3.11
        run: |
          python -m pip install ".[lint]"
          python -m black .
          python -m ruff --fix .
        continue-on-error: true